# Intro to Numpy

### Importing library

In [0]:
# Import library
import numpy as np

### Scalars in Numpy

In [0]:
# Numpy array with just a scalar
s=np.array(5)

In [0]:
s.shape

()

In [0]:
x=s+3
x

8

### Vectors in Numpy

In [0]:
v = np.array([1,2,3])
v.shape

(3,)

In [0]:
# To access an element within the vector using indices
x = v[1]
x

2

In [0]:
# To access elements onward the second item
v[1:]

array([2, 3])

### Matrices in Numpy

In [0]:
m = np.array([[1,2,3], [4,5,6], [7,8,9]])
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [0]:
m.shape

(3, 3)

In [0]:
# To access 6
m[1,2]

6

### Tensors in Numpy

In [0]:
t = np.array([[[[1],[2]],[[3],[4]],[[5],[6]]],[[[7],[8]],\
    [[9],[10]],[[11],[12]]],[[[13],[14]],[[15],[16]],[[17],[17]]]])

In [0]:
t.shape

(3, 3, 2, 1)

In [0]:
# To access in tensor
t[2][1][1][0]

16

### Reshape matrices

In [0]:
v = np.array([1,2,3,4])

v.shape

(4,)

In [0]:
x = v.reshape(1,4)
x.shape

(1, 4)

Other forms of the same code

In [0]:
x = v[None, :]
x.shape

(1, 4)

In [0]:
x = v[:,None]
x.shape

(4, 1)

### Basic operations with numpy

In [0]:
# Sum
values = [1,2,3,4,5]
values = np.array(values) + 5
values

array([ 6,  7,  8,  9, 10])

In [0]:
# Multiplication but another notation
x = np.multiply(values, 5)
x

array([30, 35, 40, 45, 50])

In [0]:
# To make every item zero for every dimension
m*=0
m

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [0]:
# Sum between matrices, with compatible shape
a = np.array([[1,3],[5,7]])
b = np.array([[2,4],[6,8]])
a + b

array([[ 3,  7],
       [11, 15]])

### Numpy matrix multiplication

In [46]:
m = np.array([[1,2,3],[4,5,6]])
m

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
n = m * 0.25
n

array([[0.25, 0.5 , 0.75],
       [1.  , 1.25, 1.5 ]])

In [48]:
m * n

array([[0.25, 1.  , 2.25],
       [4.  , 6.25, 9.  ]])

In [49]:
# equivalent to m * n
np.multiply(m, n)

array([[0.25, 1.  , 2.25],
       [4.  , 6.25, 9.  ]])

### Matrix product

In [50]:
a = np.array([[1,2,3,4],[5,6,7,8]])
a.shape

(2, 4)

In [51]:
b = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
b.shape


(4, 3)

In [52]:
c = np.matmul(a, b)
c

array([[ 70,  80,  90],
       [158, 184, 210]])

In [54]:
# Dot function is the same as matmul for matrices of 2 dimensions
np.dot(a,b)

array([[ 70,  80,  90],
       [158, 184, 210]])

### Matrix transpose

In [55]:
m = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
m

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [56]:
m.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [57]:
m_t = m.T
m_t[3][1] = 200
m_t

array([[  1,   5,   9],
       [  2,   6,  10],
       [  3,   7,  11],
       [  4, 200,  12]])

In [59]:
# If we modify the transpose, the real matrix is modified too
m

array([[  1,   2,   3,   4],
       [  5,   6,   7, 200],
       [  9,  10,  11,  12]])