# Intro to Numpy

### Importing library

In [2]:
# Import library
import numpy as np

### Scalars in Numpy

In [3]:
# Numpy array with just a scalar
s=np.array(10)

In [4]:
s.shape

()

### Vectors in Numpy

In [6]:
mat = np.array([1,2,3])
mat.shape

(3,)

In [7]:
# To access an element within the vector using indices
mat[1]

2

In [8]:
# To access elements onward the second item
mat[1:]

array([2, 3])

### Matrices in Numpy

In [9]:
mat = np.array([[1,2,3], [4,5,6], [7,8,9]])
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
mat.shape

(3, 3)

In [12]:
# To access 9
mat[2,2]

9

### Tensors in Numpy

In [13]:
t = np.array([[[[1],[2]],[[3],[4]],[[5],[6]]],[[[7],[8]],\
    [[9],[10]],[[11],[12]]],[[[13],[14]],[[15],[16]],[[17],[17]]]])
t.shape

(3, 3, 2, 1)

In [14]:
# To access in tensor
t[2][1][1][0]

16

### Reshape matrices

In [15]:
v = np.array([1,2,3,4])
v.shape

(4,)

In [16]:
x = v.reshape(1,4)
x.shape

(1, 4)

Other forms of the same code

In [17]:
x = v[None, :]
x.shape

(1, 4)

In [18]:
x = v[:,None]
x.shape

(4, 1)

### Basic operations with numpy

In [19]:
# Sum
values = [1,2,3,4,5]
values = np.array(values) + 5
values

array([ 6,  7,  8,  9, 10])

In [20]:
# Multiplication but another notation
x = np.multiply(values, 5)
x

array([30, 35, 40, 45, 50])

In [23]:
# To make every item zero for every dimension
mat*=0
mat

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [24]:
# Sum between matrices, with compatible shape
a = np.array([[1,3],[5,7]])
b = np.array([[2,4],[6,8]])
a + b

array([[ 3,  7],
       [11, 15]])

### Numpy matrix multiplication

In [25]:
m = np.array([[1,2,3],[4,5,6]])
m

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
n = m * 0.25
n

array([[0.25, 0.5 , 0.75],
       [1.  , 1.25, 1.5 ]])

In [27]:
m * n

array([[0.25, 1.  , 2.25],
       [4.  , 6.25, 9.  ]])

In [28]:
# equivalent to m * n
np.multiply(m, n)

array([[0.25, 1.  , 2.25],
       [4.  , 6.25, 9.  ]])

### Matrix product

In [29]:
a = np.array([[1,2,3,4],[5,6,7,8]])
a.shape

(2, 4)

In [30]:
b = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
b.shape


(4, 3)

In [31]:
c = np.matmul(a, b)
c

array([[ 70,  80,  90],
       [158, 184, 210]])

In [32]:
# Dot function is the same as matmul for matrices of 2 dimensions
np.dot(a,b)

array([[ 70,  80,  90],
       [158, 184, 210]])

### Matrix transpose

In [33]:
m = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
m

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [34]:
m.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [35]:
m_t = m.T
m_t[3][1] = 200
m_t

array([[  1,   5,   9],
       [  2,   6,  10],
       [  3,   7,  11],
       [  4, 200,  12]])

In [36]:
# If we modify the transpose, the real matrix is modified too
m

array([[  1,   2,   3,   4],
       [  5,   6,   7, 200],
       [  9,  10,  11,  12]])